# Generated by Django 4.2.2 on 2023-07-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=0, verbose_name='год регистрации пробега')),
                ('milage', models.PositiveSmallIntegerField(default=0, verbose_name='пробег')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.car')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.motorcycle')),
            ],
            options={
                'verbose_name': 'пробег',
                'verbose_name_plural': 'пробеги',
            },
        ),
    ]
